plugins {
    id 'multiloader'
}

multiLoader.neo() {
    neoVersion.set("${neo_version}")
}

jar {
    from project(":common").sourceSets.main.output
}

publishing.publications.mavenJava.from components.java

sourceSets.main.resources { srcDir project(":common").file('src/generated/resources') }

dependencies {
    implementation("com.unrealdinnerbone:trenzalore-neo:${project.property("trenzalore_version")}+mc${project.property("minecraft_version")}")
}
